[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "loris"
description = "Loris is an open-source C++ class library for sound analysis, manipulation, and synthesis using the Reassigned Bandwidth-Enhanced Additive Sound Model."
keywords = ["loris", "build", "c", "c++", "swig"]
license = {text = "https://github.com/charlesneimog/loris/blob/main/LICENSE"}
readme = "README.md"
classifiers = [
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Programming Language :: C",
  "Programming Language :: C++",
  "Programming Language :: Python",
  "Operating System :: OS Independent",
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",
]
dynamic = ["version"]

[tool.scikit-build]
wheel.py-api = "py2.py3"
wheel.expand-macos-universal-tags = true
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
wheel.install-dir = "loris/data"

[tool.cibuildwheel]
build = "cp39-*"
test-command = [
  "swig -version",
  "swig -pcreversion",
  "swig -help",
]
environment.PIP_ONLY_BINARY = ":all:"

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux1"
manylinux-i686-image = "manylinux1"

[project.scripts]
loris = "loris:loris"

[project.urls]
Homepage = "https://www.cerlsoundgroup.org/Loris/"
Download = "https://sourceforge.net/projects/loris/"
"Source Code" = "https://github.com/charlesneimog/loris"
"Bug Tracker" = "https://github.com/charlesneimog/loris/issues"

[tool.setuptools_scm]
write_to = "src/loris/_version.py"
