---
name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build-unix:
    name: Build on ${{ matrix.os }} (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]
        python-version: [3.12, 3.13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch || 'x64' }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install scikit-build-core swig 
      - name: Build package
        run: python -m build --wheel
      - name: Upload wheel to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: loris-wheel
          path: dist/*.whl
  build-windows:
    name: Build on ${{ matrix.os }} (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-name: [3.12, 3.13]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch || 'x64' }}
      - name: Set up Msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: make mingw-w64-x86_64-gcc mingw64/mingw-w64-x86_64-cmake
          update: false
      - name: Add mingw64 on path
        run: |
          echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH
          echo "C:/msys64/mingw64/lib" >> $GITHUB_PATH
          echo "::add-path::/mingw64/bin"
          echo "::add-path::/mingw64/lib"
      - name: Install dependencies
        run: |
          pip install build
          pip install scikit-build-core swig 
      - name: Build package
        run: python -m build --wheel
      - name: Upload wheel to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: loris-wheel
          path: dist/*.whl
